#!/bin/bash

RUN_DIR=/var/vcap/sys/run/nginx
LOG_DIR=/var/vcap/sys/log/nginx
#CONF_DIR=/var/vcap/jobs

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR
    chown -R vcap:vcap $RUN_DIR $LOG_DIR

    # copy config file in nginx package
    cp /var/vcp/jobs/nginx/config/nginx.config /var/vcap/packages/nginx/nginx.config

    echo $$ > $PIDFILE

    /var/vcap/packages/nginx/sbin/nginx

    ;;

  stop)
    kill -9 `cat $PIDFILE`
    rm -f $PIDFILE

    ;;

  *)
    echo "Usage: ctl {start|stop}" ;;

esac
