name: nginx
director_uuid: 63ddb6a6-d6fe-40e1-b16b-2ff6b2034c79

releases:
- {name: nginx-v1, version: 0+dev.25}

resource_pools:
- name: nginx-server
  network: default
  stemcell:
    alias: bosh-warden-boshlite-ubuntu-trusty-go_agent
    os: ubuntu-trusty
    version: 3312.17

networks:
  - name: default
    type: manual
    subnets:
    - range: 10.10.0.0/24
      gateway: 10.10.0.1

compilation:
  workers: 2
  network: default
  reuse_compilation_vms: true

disk_pools:
- name: default
  disk_size: 2000

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-100000
  update_watch_time: 1000-30000

jobs:
  - name: nginx
    instances: 1
    templates:
    - {name: nginx, release: nginx-v1}
    persistent_disk: 1000
    resource_pool: nginx-server
    networks:
    - name: default

properties:
  nginx:
    events:
      worker_connections: 1024
    http:
      tcp_nopush: on
      keepalive_timeout: 65
      server:
        listen: 80
        server_name: localhost
